### ISSUE TITLE
How use the script with a specific model by uid?

### ISSUE THREAD

**Issue by p4535992** [mauricesvay/SketchfabDataApi#1]
Hi, sorry to bother you, i'm a little lost on the code how can is use `client.apis.models.get_v3_models()`  and the other functions for a specific model by uid?

**Comment by mauricesvay** [comment]
Hey @p4535992 
I've updated the lib and added an example here:
https://github.com/mauricesvay/SketchfabDataApi/blob/master/test/node/test.js#L18-L25
